=== aero-mod/addons/$$schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "aero-addon",
    "title": "Addon Listing",
    "description": "A listing for an aero addon",
    "type": "object",
    "properties": {
        "added": {
            "description": "serialised Date",
            "type": "string"
        },
        "id": {
            "description": "The unique identifier for the addon.",
            "type": "string"
        },
        "title": {
            "description": "The title of the addon.",
            "type": "string"
        },
        "description": {
            "description": "The description of the addon.",
            "type": "string"
        },
        "author": {
            "description": "The author of the addon.",
            "type": "string"
        },
        "repository": {
            "description": "The GitHub repository path. (e.g. TheCommieAxolotl/aero-addons)",
            "type": "string"
        },
        "path": {
            "description": "The path to the addon inside the GitHub repository. (e.g. plugins/ExampleAddon.ts or themes/ExampleTheme/)",
            "type": "string"
        },
        "sha256": {
            "description": "The commit hash of the verified version of the addon.",
            "type": "string"
        }
    },
    "required": ["id", "added", "title", "description", "repository", "path", "sha256"]
}

=== aero-mod/addons/theme/Primer.json
{
    "$schema": "../$$schema.json",
    "added": "2023-7-1:05:12:00",
    "id": "primer",
    "title": "Primer",
    "description": "A theme that makes Discord look like GitHub's Primer design system.",
    "author": "TheCommieAxolotl",
    "repository": "TheCommieAxolotl/aero-addons",
    "sha256": "3bf77d70aaf4ccb6b8fac190fe457b8f027e2448",
    "path": "themes/Primer"
}

=== aero-mod/addons/plugin/prettyLinks.json
{
    "$schema": "../$$schema.json",
    "added": "2023-7-1",
    "id": "prettyLinks",
    "title": "Pretty Links",
    "description": "Remove release channel information from message links.",
    "author": "TheCommieAxolotl",
    "repository": "TheCommieAxolotl/aero-addons",
    "sha256": "d651ab5ac412d6727dcf24cfa0bb1fa646490e13",
    "path": "plugins/prettylinks.ts"
}

=== aero-mod/addons/plugin/betterTyping.json
{
    "$schema": "../$$schema.json",
    "added": "2023-7-16:03:59:00",
    "id": "betterTyping",
    "title": "Better Typing",
    "description": "Enhance the typing indicator to be more useful. (Show Role Colors, Clickable Usernames)",
    "author": "TheCommieAxolotl",
    "repository": "TheCommieAxolotl/aero-addons",
    "sha256": "8dff34a246b3fd9850f4dd1e83f1101a91527318",
    "path": "plugins/betterTyping.tsx"
}

=== aero-mod/addons/plugin/unmask.json
{
    "$schema": "../$$schema.json",
    "added": "2023-7-2:03:01:00",
    "id": "unmask",
    "title": "Unmask",
    "description": "Shows users with nicknames' usernames in chat.",
    "author": "TheCommieAxolotl",
    "repository": "TheCommieAxolotl/aero-addons",
    "sha256": "325b960e7b9219a7c0924c251bfe54988c42f4e2",
    "path": "plugins/unmask.tsx"
}

=== aero-mod/addons/_plugins.json
[{"$schema":"../$$schema.json","added":"2023-7-1:07:49:00","id":"prettyLinks","title":"Pretty Links","description":"Remove release channel information from message links.","author":"TheCommieAxolotl","repository":"TheCommieAxolotl/aero-addons","sha256":"170d535d0253dbc1c6b8434e3bbd36b8431b2f67","path":"plugins/prettylinks.ts"},{"$schema":"../$$schema.json","added":"2023-7-1:07:49:00","id":"previewMessage","title":"Preview Message","description":"Allows you to preview a message before you send it.","author":"TheCommieAxolotl","repository":"TheCommieAxolotl/aero-addons","sha256":"170d535d0253dbc1c6b8434e3bbd36b8431b2f67","path":"plugins/PreviewMessage.tsx"},{"$schema":"../$$schema.json","added":"2023-7-2:03:01:00","id":"unmask","title":"Unmask","description":"Shows users with nicknames' usernames in chat.","author":"TheCommieAxolotl","repository":"TheCommieAxolotl/aero-addons","sha256":"325b960e7b9219a7c0924c251bfe54988c42f4e2","path":"plugins/unmask.tsx"}]

=== aero-mod/addons/plugin/betterCodeblocks.json
{
    "$schema": "../$$schema.json",
    "added": "2023-7-16:03:59:00",
    "id": "betterCodeblocks",
    "title": "Better Codeblocks",
    "description": "Enhances Discord's codeblocks with language indicators, copy buttons, and more.",
    "author": "TheCommieAxolotl",
    "repository": "TheCommieAxolotl/aero-addons",
    "sha256": "faf79449fe7de89fe5bd748464a790b5deb48dd4",
    "path": "plugins/betterCodeblocks.tsx"
}
